version: '3.9'

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - HTTPS=${HTTPS:-false}
      - UPLOAD_FOLDER=/app/uploads
      - MAX_UPLOAD_MB=${MAX_UPLOAD_MB:-500}
      - FLASK_DEBUG=false
    volumes:
      - ${UPLOAD_FOLDER}:/app/uploads
      - ${DATA_DIRECTORY}:/app/instance
    ports:
      - 5000:5000
