version: '3.9'

services:
  app:
    image: pixelvault:latest
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile.prod
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - HTTPS=${HTTPS:-false}
      - UPLOAD_FOLDER=/app/uploads
      - DATABASE_URL=sqlite:////app/instance/pixelvault.db
      - MAX_UPLOAD_MB=${MAX_UPLOAD_MB:-500}
      - MAX_INFLIGHT_UPLOAD_MB_PER_USER=${MAX_INFLIGHT_UPLOAD_MB_PER_USER:-1500}
      - FLASK_DEBUG=false
    volumes:
      - ${UPLOAD_FOLDER:?UPLOAD_FOLDER not set}:/app/uploads
      - ${DATABASE_PATH:?DATABASE_PATH not set}:/app/instance
    ports:
      - 5000:5000
    #expose:
    #  - "5000"
    networks:
      - internal

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro           # Put your SSL certs here
      - ${UPLOAD_FOLDER:?UPLOAD_FOLDER not set}:/app/uploads:ro
    depends_on:
      - app
    networks:
      - internal
    profiles:
      - nginx

networks:
  internal:
